name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.26.4"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build binaries
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags="-H=windowsgui -s -w" -o bin/cs2kz-app.exe .

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/cs2kz-app.exe
          generate_release_notes: true